###

POST https://serverlessohmanagementapi.trafficmanager.net/api/team/registerEventHub
content-type: application/json 

{
    "teamTableNumber" : 1,
    "eventHubConnectionString" : "Endpoint=sb://organigz.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=5A1WDvoN/132i5o+fk6Q/E41+mQBRl3hc4h0/N7xR+4=",
    "eventHubName" : "bighub"
}


###

POST https://serverlessohmanagementapi.trafficmanager.net/api/team/boost/1


### 

POST http://localhost:7071/api/CreateRating/
content-type: application/json

{
    name : "tim",
    userNotes: "This tastes bad"
}

###

POST https://eventhubfuncy.azurewebsites.net/api/CreateRating/
content-type: application/json

{
    name : "tim",
    userNotes: "This tastes bad"
}

###